// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kohvocnrowelinsmcikz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvaHZvY25yb3dlbGluc21jaWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTU5NjQsImV4cCI6MjA2NTQ5MTk2NH0.zP-UcHY7lqFyJaS2KMqhIVOiWNdpw5TueNQBLV5xdz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);